#define N_Sensors 4

#define BLACK_SENSORS_SIDE 0
#define BLACK_SENSOR_MIDDLE 2
#define YELLOW_SENSORS_SIDE 6
#define YELLOW_SENSOR_MIDDLE 5

#define MAX_GAME_LENGTH_MILLIS 90000
#define FINAL_ACTION_DELAY_MILLIS 82000

#define TEST_OR_GAME_PIN
